### ISSUE TITLE
Feature Request: Smart WP username scraping and cracking

### ISSUE THREAD

**Issue by spmedia** [leo-lb/wpbrute-rs#3]
Leo, cool script. I've always been fascinated with password cracking.

I'm just going to write the idea here and the logic behind it because I'm too dumb to figure out how to do this in Rust myself atm. Instead of using the default username of admin or wp-admin, I figured this would be a smarter way to go about doing it and yield higher results/successes. 

I tested this on the most up-to-date WordPress (5.3) and it still works as of this comment.

You can take the URL given by the user running this script and append /wp-json/wp/v2/users to the end of it and it will list all current users in JSON format. A successful attempt will look like [this ](https://blog.feedspot.com/wp-json/wp/v2/users), [this](https://theblondeabroad.com/wp-json/wp/v2/users), or [this](https://solotravelerworld.com/wp-json/wp/v2/users). The username is contained in the **"slug":** section.

So you will then scrape all of the slug usernames out of this list and save them to a usernames.txt or whatever and then start cracking using those usernames. If no usernames are found this way, it can fallback to the defaults of admin or wp-admin.

Issues:
A plugin by Sucuri called [Sucuri Security](https://wordpress.org/plugins/sucuri-scanner/) will block this, for an example, see the error message it gives here:  https://www.browneyedbaker.com/wp-json/wp/v2/users

An error received sometimes:
{"code":"rest_user_cannot_view","message":"Sorry, you are not allowed to list users.","data":{"status":401}}
I'm not sure if this is caused by another plugin (like WordFence) or what exactly.

Misc notes:
These JSON results will also sometimes contain user emails and Gravatar profile images that could be used for further OSINT or research.

**Comment by llebout** [comment]
Hello, thanks for your interest!
Interesting trick!
The username parameter is explicitly configurable with the `-u` command line switch. I did not intend to make this tool do things such as user enumeration, other tools like [WPScan](https://github.com/wpscanteam/wpscan) do this very well and I recommend using those to perform user enumeration and later use this tool to perform a faster bruteforce!
