### ISSUE TITLE
failed to resolve: could not find `RedirectPolicy` in `reqwest`

### ISSUE THREAD

**Issue by personanomada** [leo-lb/wpbrute-rs#5]
Trying to compile/install on mac, but get this each time.

**Comment by llebout** [comment]
Fixed in https://github.com/leo-lb/wpbrute-rs/commit/eef5bb57df12246fca582e01b2088d5361b4eaab

**Comment by personanomada** [comment]
Sorry if I sound like an idiot, but how do I resolve the issue?

**Comment by personanomada** [comment]
Nevermind, all I had to do is run the install again. Thanks!
